import type { Prompt } from "@/types";

export const MOCK_PROMPTS: Prompt[] = [
  {
    id: "1",
    slug: "cinematic-indian-woman-portrait",
    title: "Cinematic Indian Woman Portrait",
    prompt_text:
      "A stunning Indian woman, traditional silk saree in deep jewel tones, golden hour light, cinematic bokeh background, Bollywood aesthetic, hyperrealistic, shot on Hasselblad, 85mm lens, f/1.4, warm tones --ar 4:5 --v 6.1 --style raw",
    prompt_hash: "hash1",
    ai_tool: "midjourney",
    category: "portrait",
    style: "cinematic",
    mood: "warm",
    aspect_ratio: "4:5",
    quality_score: 9,
    is_premium: false,
    is_nsfw: false,
    is_approved: true,
    views: 12400,
    copies: 3200,
    likes_count: 841,
    saves_count: 290,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "img1",
        prompt_id: "1",
        image_url: "https://picsum.photos/seed/portrait1/400/500",
        cdn_url: "https://picsum.photos/seed/portrait1/400/500",
        is_primary: true,
        width: 400,
        height: 500,
        created_at: new Date().toISOString(),
      },
    ],
    tags: [{ id: "t1", name: "bollywood", slug: "bollywood", count: 320 }],
  },
  {
    id: "2",
    slug: "neon-cyberpunk-cityscape-reels",
    title: "Neon Cyberpunk Cityscape for Reels",
    prompt_text:
      "Futuristic Mumbai skyline, neon lights reflecting on wet streets, cyberpunk aesthetic, rain, night time, ultra detailed, cinematic lighting, 9:16 vertical format, vibrant pink and blue neons --ar 9:16 --v 6.1",
    prompt_hash: "hash2",
    ai_tool: "midjourney",
    category: "reels",
    style: "neon",
    mood: "neon",
    aspect_ratio: "9:16",
    quality_score: 8,
    is_premium: false,
    is_nsfw: false,
    is_approved: true,
    views: 8900,
    copies: 2100,
    likes_count: 543,
    saves_count: 180,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "img2",
        prompt_id: "2",
        image_url: "https://picsum.photos/seed/neon2/360/640",
        cdn_url: "https://picsum.photos/seed/neon2/360/640",
        is_primary: true,
        width: 360,
        height: 640,
        created_at: new Date().toISOString(),
      },
    ],
    tags: [{ id: "t2", name: "cyberpunk", slug: "cyberpunk", count: 210 }],
  },
  {
    id: "3",
    slug: "anime-girl-cherry-blossoms",
    title: "Anime Girl Under Cherry Blossoms",
    prompt_text:
      "Anime girl, cherry blossom petals falling, soft pastel colors, Studio Ghibli style, ethereal lighting, detailed eyes, flowing hair, spring morning, masterpiece quality --ar 1:1 --niji 6",
    prompt_hash: "hash3",
    ai_tool: "midjourney",
    category: "anime",
    style: "anime",
    mood: "pastel",
    aspect_ratio: "1:1",
    quality_score: 9,
    is_premium: false,
    is_nsfw: false,
    is_approved: true,
    views: 21000,
    copies: 5400,
    likes_count: 1200,
    saves_count: 430,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "img3",
        prompt_id: "3",
        image_url: "https://picsum.photos/seed/anime3/400/400",
        cdn_url: "https://picsum.photos/seed/anime3/400/400",
        is_primary: true,
        width: 400,
        height: 400,
        created_at: new Date().toISOString(),
      },
    ],
    tags: [{ id: "t3", name: "ghibli", slug: "ghibli", count: 150 }],
  },
  {
    id: "4",
    slug: "dark-fantasy-warrior-woman",
    title: "Dark Fantasy Warrior Woman",
    prompt_text:
      "Epic dark fantasy female warrior, ornate black armour with gold filigree, glowing magical sword, dramatic storm clouds, volumetric god rays, hyperdetailed, fantasy art style, cinematic composition --ar 4:5 --v 6.1 --style raw --q 2",
    prompt_hash: "hash4",
    ai_tool: "midjourney",
    category: "fantasy",
    style: "cinematic",
    mood: "dark",
    aspect_ratio: "4:5",
    quality_score: 10,
    is_premium: true,
    is_nsfw: false,
    is_approved: true,
    views: 34000,
    copies: 8900,
    likes_count: 2300,
    saves_count: 890,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "img4",
        prompt_id: "4",
        image_url: "https://picsum.photos/seed/fantasy4/400/500",
        cdn_url: "https://picsum.photos/seed/fantasy4/400/500",
        is_primary: true,
        width: 400,
        height: 500,
        created_at: new Date().toISOString(),
      },
    ],
    tags: [{ id: "t4", name: "warrior", slug: "warrior", count: 98 }],
  },
  {
    id: "5",
    slug: "minimalist-product-photography",
    title: "Minimalist Product Photography",
    prompt_text:
      "Luxury perfume bottle, minimalist white studio background, soft shadows, product photography, commercial grade, 8K resolution, precise lighting setup, DALL-E 3 style",
    prompt_hash: "hash5",
    ai_tool: "dalle",
    category: "product",
    style: "minimal",
    mood: "cool",
    aspect_ratio: "1:1",
    quality_score: 8,
    is_premium: false,
    is_nsfw: false,
    is_approved: true,
    views: 6700,
    copies: 1800,
    likes_count: 320,
    saves_count: 140,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "img5",
        prompt_id: "5",
        image_url: "https://picsum.photos/seed/product5/400/400",
        cdn_url: "https://picsum.photos/seed/product5/400/400",
        is_primary: true,
        width: 400,
        height: 400,
        created_at: new Date().toISOString(),
      },
    ],
    tags: [{ id: "t5", name: "product", slug: "product", count: 76 }],
  },
  {
    id: "6",
    slug: "watercolor-taj-mahal-sunrise",
    title: "Watercolor Taj Mahal at Sunrise",
    prompt_text:
      "Taj Mahal at golden sunrise, soft watercolor painting style, pastel pinks and golds reflecting in the pool, dreamy atmosphere, traditional Indian art influence, loose brush strokes, warm palette --ar 16:9 --v 6.1",
    prompt_hash: "hash6",
    ai_tool: "midjourney",
    category: "indian",
    style: "watercolor",
    mood: "warm",
    aspect_ratio: "16:9",
    quality_score: 9,
    is_premium: false,
    is_nsfw: false,
    is_approved: true,
    views: 15600,
    copies: 4100,
    likes_count: 980,
    saves_count: 340,
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "img6",
        prompt_id: "6",
        image_url: "https://picsum.photos/seed/india6/640/360",
        cdn_url: "https://picsum.photos/seed/india6/640/360",
        is_primary: true,
        width: 640,
        height: 360,
        created_at: new Date().toISOString(),
      },
    ],
    tags: [{ id: "t6", name: "india", slug: "india", count: 430 }],
  },
  {
    id: "7",
    slug: "stable-diffusion-3d-character",
    title: "3D Cartoon Character for Social Media",
    prompt_text:
      "Cute 3D cartoon character, big expressive eyes, smooth rounded shapes, vibrant colors, Pixar style, white background, 3D render, octane render, subsurface scattering, cheerful expression",
    prompt_hash: "hash7",
    ai_tool: "stable_diffusion",
    category: "abstract",
    style: "3d",
    mood: "vibrant",
    aspect_ratio: "1:1",
    quality_score: 7,
    is_premium: false,
    is_nsfw: false,
    is_approved: true,
    views: 4300,
    copies: 890,
    likes_count: 210,
    saves_count: 67,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "img7",
        prompt_id: "7",
        image_url: "https://picsum.photos/seed/3d7/400/400",
        cdn_url: "https://picsum.photos/seed/3d7/400/400",
        is_primary: true,
        width: 400,
        height: 400,
        created_at: new Date().toISOString(),
      },
    ],
    tags: [{ id: "t7", name: "3d", slug: "3d", count: 88 }],
  },
  {
    id: "8",
    slug: "flux-fashion-editorial",
    title: "High Fashion Editorial Portrait",
    prompt_text:
      "High fashion editorial photograph, model in avant-garde outfit, dramatic studio lighting, Vogue magazine style, black and white with selective color, hyperrealistic skin texture, sharp focus --ar 4:5",
    prompt_hash: "hash8",
    ai_tool: "flux",
    category: "fashion",
    style: "realistic",
    mood: "bw",
    aspect_ratio: "4:5",
    quality_score: 9,
    is_premium: true,
    is_nsfw: false,
    is_approved: true,
    views: 18900,
    copies: 5100,
    likes_count: 1450,
    saves_count: 520,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "img8",
        prompt_id: "8",
        image_url: "https://picsum.photos/seed/fashion8/400/500",
        cdn_url: "https://picsum.photos/seed/fashion8/400/500",
        is_primary: true,
        width: 400,
        height: 500,
        created_at: new Date().toISOString(),
      },
    ],
    tags: [{ id: "t8", name: "editorial", slug: "editorial", count: 120 }],
  },
];
